CREATE TABLE Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);
ALTER TABLE users ADD COLUMN  security_code VARCHAR(255);
ALTER TABLE users ADD COLUMN  is active BOOLEAN DEFAULT 0;


